# NOTE: Generated By HttpRunner v3.1.4
# FROM: member_getMemberCardList.har

"""
currentPage integer($int64) (query) 当前页数
pageSize integer($int64) (query) 每页记录数
qp-createTime-ge string (query) 注册开始时间
qp-createTime-le string (query) 注册结束时间
qp-id-eq string (query) 用户ID
qp-phone-eq string (query) 手机号
qp-tag-eq string (query) 标签id
qp-templateGroupId-eq string (query)  会员体系id
sorter string (query) 排序条件 desc-字段名或者asc-字段名
sso_sessionid string (header) sessionid
x-tenant-id * string (header) tenant Default value : 2

"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase, Parameters
import pytest
from testcases.api.ops.opsLogin_test import TestCaseOpslogin as Login


class TestCaseMemberGetmembercardlist(HttpRunner):

    @pytest.mark.parametrize(
        "param",
        Parameters({
            "userName-password-verifyCode1-regType": "${parameterize(common.csv)}",
            "currentPage-pageSize-qp_barCode_eq-qp_brandId_in-qp_categoryId_in-qp_classId_in-qp_combination_eq-qp_labelIds_like-qp_name_like-qp_ownerId_eq-qp_skuCode_eq-qp_storeCode_eq-skuNameOrCode-sorter": "${parameterize(testcases/api/ops/item/getSkuList.csv)}",
        })
    )
    def test_start(self, param) -> "HttpRunner":
        super().test_start(param)

    config = (
        Config("登录ops环境")
        .base_url("${get_base_url()}")
        .variables(**{
            "x_tenant_id": "2",  # tenant Default value : 2     必填选项  header部分
            "x_app_id": "200",
        })
        .export(*["token", "sessionId"])
        .verify(False)
    )

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(Login)
            .export(*["sessionId", "token"])
        ),
        Step(
            RunRequest("查询一系列对象，也就是列表")
            .get("/ops/api/member/getMemberCardList")
            .with_params(**{"currentPage": "1", "pageSize": "10"})
            .with_headers(
                **{
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "Token": "$token",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
    ]


if __name__ == "__main__":
    TestCaseMemberGetmembercardlist().test_start()
