# NOTE: Generated By HttpRunner v3.1.4
# FROM: 优惠券新增_提交关闭.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import pytest
from httprunner import Parameters
import datetime
import uuid


class TestCaseAddAndDeleteCoupon(HttpRunner):

    @pytest.mark.parametrize(
        'param',
        Parameters(
            {
                "x_app_id": ["200"],
                "x_tenant_id": ["2"],
                "password": ["200622"],
                "regType": [4],
                "userName": ["opsAdmin"],
                "verifyCode": ["1234"],
                "ticketName": ["api接口自动化{}".format(uuid.uuid4().__str__().replace('-', ''))],
                "ticketDesc": ["api接口自动化测试新增优惠券，优惠券说明api接口自动化测试新增优惠券，优惠券说明api接口自动化测试新增优惠券，优惠券说明api接口自动化测试新增优惠券，优惠券说明api接口自动化测试新增优惠券，优惠券说明api接口自动化测试新增优惠券，优惠券说明a"],
                "releaseTime": ["{}T10:06:41.507Z".format((datetime.datetime.utcnow() - datetime.timedelta(days=-1)).strftime('%Y-%m-%d'))],
                "stopTime": ["{}T23:59:59.000Z".format((datetime.datetime.utcnow() - datetime.timedelta(days=-30)).strftime('%Y-%m-%d'))],
                "file_path": ['./image/reduction.jpg']
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("TestCase优惠券新增提交关闭")
        .base_url("${get_base_url()}")
        .verify(False)
        .export(*["token", "verifyId", "sessionId", "id", "activityNo", "createUserName", "modifyUserName", "ticketCode"])
    )

    teststeps = [
        Step(
            RunRequest("/ops/api/web/getVerificationCode")
            .get("/ops/api/web/getVerificationCode?")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36",
                    "Token": "",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .extract()
            .with_jmespath("body.data.verifyId", "verifyId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/web/login")
            .post("/ops/api/web/login")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36",
                    "Token": "",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "userName": "$userName",
                    "password": "$password",
                    "verifyCode": "$verifyCode",
                    "verifyId": "$verifyId",
                    "regType": "$regType",
                }
            )
            .extract()
            .with_jmespath("body.data.token", "token")
            .with_jmespath("body.data.sessionId", "sessionId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/query")
            .get("/ops/api/ticket/query?")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/sku/getSkuList")
            .get("/ops/api/sku/getSkuList")
            .with_params(**{"pageSize": "10", "currentPage": "1"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/upload")
            .with_variables(
                **{
                    "file_path": "$file_path",
                    "m_encoder": "${multipart_encoder(file=$file_path)}",
                }
            )
            .post("/ops/api/upload")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "x-tenant-id": "$x_tenant_id",
                    "X-Requested-With": "XMLHttpRequest",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "${multipart_content_type($m_encoder)}",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("$m_encoder")
            .extract()
            .with_jmespath('body.data', 'ticketUrl')
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/addTicket")
            .post("/ops/api/ticket/addTicket")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "ticketName": "$ticketName",
                    "ticketUrl": "$ticketUrl",
                    "ticketDesc": "$ticketDesc",
                    "releaseTime": "$releaseTime",
                    "stopTime": "$stopTime",
                }
            )
            .extract()
            .with_jmespath('body.data.id', 'id')
            .with_jmespath('body.data.activityNo', "activityNo")
            .with_jmespath('body.data.createUserName', "createUserName")
            .with_jmespath('body.data.modifyUserName', "modifyUserName")
            .with_jmespath('body.data.ticketCode', "ticketCode")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/editTicket")
            .patch("/ops/api/ticket/editTicket")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "id": "$id",
                    "ticketCode": "$ticketCode",
                    "ticketAmount": "100",
                    "ticketOccupied": 0,
                    "ticketUsed": 0,
                    "releaseTime": "$releaseTime",
                    "stopTime": "$stopTime",
                    "activityNo": "$activityNo",
                    "ticketType": 1,
                    "ticketDesc": "$ticketDesc",
                    "ticketStatus": 0,
                    "ticketRange": None,
                    "releaseType": 2,
                    "ticketUrl": "$ticketUrl",
                    "effectivetimeStart": None,
                    "effectivetimeEnd": None,
                    "ticketRules": '{"configurations":{"CHANNEL_RULE":{"values":[{"enable":true,"name":"电商","type":[{"enable":true,"name":"全部店铺","value":"1"},{"enable":false,"name":"部分店铺","value":"2"}],"value":"1"}],"name":"活动平台","id":"","desc":"活动平台","group":"group"},"PROMOTION_RULE":{"values":[{"range":"1000","value":"1"}],"name":"优惠券活动规则","id":"overoff","desc":"满减优惠券，满range元减value;满折优惠券，满range元折value;单品优惠券，range为0元减value;","group":"group"},"USER_RULE":{"values":[{"enable":true,"name":"黄金会员","value":"LV4"},{"enable":false,"name":"白银会员","value":"LV3"},{"enable":false,"name":"青铜会员","value":"LV2"},{"enable":false,"name":"铂金会员","value":"LV5"},{"enable":false,"name":"普通会员","value":"LV1"}],"name":"会员等级","id":"","desc":"活动会员等级","group":"group"},"USE_RANGE_TYPE":{"values":[{"enable":false,"name":"全部商品","value":"all"},{"enable":false,"name":"部分商品","value":"part"}],"name":"商品范围","id":"USE_RANGE_TYPE","desc":"商品范围","group":"radio"},"OVERLYING_RULE":{"values":[{"enable":true,"name":"单品活动","value":"1"},{"enable":true,"name":"订单活动","value":"2"},{"enable":false,"name":"单品优惠券","value":"3"},{"enable":false,"name":"订单优惠券","value":"4"}],"name":"叠加规则","id":"","desc":"叠加规则","group":"group"},"TICKET_GET_LIMIT_TYPE":{"values":[{"number":"2","enable":true,"name":"限制","value":"limit"}],"name":"领取限制","id":"TICKET_GET_LIMIT_TYPE","desc":"limit：个数 numer:领取限制数量","group":"radio"}}}',
                    "rejectOpinion": None,
                    "ticketChannel": None,
                    "createUserId": "1",
                    "modifyUserId": "1",
                    "ticketName": "$ticketName",
                    "platformId": "0",
                    "receiveEffectivetime": None,
                    "ticketLabelType": None,
                    "createUserName": "$createUserName",
                    "modifyUserName": "$modifyUserName",
                    "createTime": None,
                    "modifyTime": None,
                    "bg": None,
                    "ticketOwnerCode": "0",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/editTicket")
            .patch("/ops/api/ticket/editTicket")
            .with_headers(
                **{

                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "id": "$id",
                    "ticketCode": "$ticketCode",
                    "ticketAmount": 100,
                    "ticketOccupied": None,
                    "ticketUsed": None,
                    "releaseTime": "$releaseTime",
                    "stopTime": "$stopTime",
                    "activityNo": "$activityNo",
                    "ticketType": 1,
                    "ticketDesc": "$ticketDesc",
                    "ticketStatus": 0,
                    "ticketRange": 1,
                    "releaseType": 2,
                    "ticketUrl": "$ticketUrl",
                    "effectivetimeStart": None,
                    "effectivetimeEnd": None,
                    "ticketRules": '{"configurations":{"CHANNEL_RULE":{"values":[{"enable":true,"name":"电商","type":[{"enable":true,"name":"全部店铺","value":"1"},{"enable":false,"name":"部分店铺","value":"2"}],"value":"1"}],"name":"活动平台","id":"","desc":"活动平台","group":"group"},"PROMOTION_RULE":{"values":[{"range":"1000","value":"1"}],"name":"优惠券活动规则","id":"overoff","desc":"满减优惠券，满range元减value;满折优惠券，满range元折value;单品优惠券，range为0元减value;","group":"group"},"USER_RULE":{"values":[{"enable":true,"name":"黄金会员","value":"LV4"},{"enable":false,"name":"白银会员","value":"LV3"},{"enable":false,"name":"青铜会员","value":"LV2"},{"enable":false,"name":"铂金会员","value":"LV5"},{"enable":false,"name":"普通会员","value":"LV1"}],"name":"会员等级","id":"","desc":"活动会员等级","group":"group"},"USE_RANGE_TYPE":{"values":[{"enable":true,"name":"全部商品","value":"all"},{"enable":false,"name":"部分商品","value":"part"}],"name":"商品范围","id":"USE_RANGE_TYPE","desc":"商品范围","group":"radio"},"OVERLYING_RULE":{"values":[{"enable":true,"name":"单品活动","value":"1"},{"enable":true,"name":"订单活动","value":"2"},{"enable":false,"name":"单品优惠券","value":"3"},{"enable":false,"name":"订单优惠券","value":"4"}],"name":"叠加规则","id":"","desc":"叠加规则","group":"group"},"TICKET_GET_LIMIT_TYPE":{"values":[{"number":"2","enable":true,"name":"限制","value":"limit"}],"name":"领取限制","id":"TICKET_GET_LIMIT_TYPE","desc":"limit：个数 numer:领取限制数量","group":"radio"}}}',
                    "rejectOpinion": None,
                    "ticketChannel": None,
                    "createUserId": "1",
                    "modifyUserId": "1",
                    "ticketName": "$ticketName",
                    "platformId": None,
                    "receiveEffectivetime": None,
                    "ticketLabelType": None,
                    "createUserName": "$createUserName",
                    "modifyUserName": "$modifyUserName",
                    "createTime": None,
                    "modifyTime": None,
                    "bg": None,
                    "ticketOwnerCode": None,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/editTicket")
            .patch("/ops/api/ticket/editTicket")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "id": "$id",
                    "ticketCode": "$ticketCode",
                    "ticketAmount": 100,
                    "ticketOccupied": None,
                    "ticketUsed": None,
                    "releaseTime": "$releaseTime",
                    "stopTime": "$stopTime",
                    "activityNo": "$activityNo",
                    "ticketType": 1,
                    "ticketDesc": "$ticketDesc",
                    "ticketStatus": 0,
                    "ticketRange": 1,
                    "releaseType": 2,
                    "ticketUrl": "$ticketUrl",
                    "effectivetimeStart": "$releaseTime",
                    "effectivetimeEnd": "$stopTime",
                    "ticketRules": '{"configurations":{"CHANNEL_RULE":{"values":[{"enable":true,"name":"电商","type":[{"enable":true,"name":"全部店铺","value":"1"},{"enable":false,"name":"部分店铺","value":"2"}],"value":"1"}],"name":"活动平台","id":"","desc":"活动平台","group":"group"},"PROMOTION_RULE":{"values":[{"range":"1000","value":"1"}],"name":"优惠券活动规则","id":"overoff","desc":"满减优惠券，满range元减value;满折优惠券，满range元折value;单品优惠券，range为0元减value;","group":"group"},"USER_RULE":{"values":[{"enable":true,"name":"黄金会员","value":"LV4"},{"enable":false,"name":"白银会员","value":"LV3"},{"enable":false,"name":"青铜会员","value":"LV2"},{"enable":false,"name":"铂金会员","value":"LV5"},{"enable":false,"name":"普通会员","value":"LV1"}],"name":"会员等级","id":"","desc":"活动会员等级","group":"group"},"USE_RANGE_TYPE":{"values":[{"enable":true,"name":"全部商品","value":"all"},{"enable":false,"name":"部分商品","value":"part"}],"name":"商品范围","id":"USE_RANGE_TYPE","desc":"商品范围","group":"radio"},"OVERLYING_RULE":{"values":[{"enable":true,"name":"单品活动","value":"1"},{"enable":true,"name":"订单活动","value":"2"},{"enable":false,"name":"单品优惠券","value":"3"},{"enable":false,"name":"订单优惠券","value":"4"}],"name":"叠加规则","id":"","desc":"叠加规则","group":"group"},"TICKET_GET_LIMIT_TYPE":{"values":[{"number":"2","enable":true,"name":"限制","value":"limit"}],"name":"领取限制","id":"TICKET_GET_LIMIT_TYPE","desc":"limit：个数 numer:领取限制数量","group":"radio"}}}',
                    "rejectOpinion": None,
                    "ticketChannel": None,
                    "createUserId": "1",
                    "modifyUserId": "1",
                    "ticketName": "$ticketName",
                    "platformId": None,
                    "ticketLabelType": None,
                    "createUserName": "$createUserName",
                    "modifyUserName": "$modifyUserName",
                    "createTime": None,
                    "modifyTime": None,
                    "bg": None,
                    "ticketOwnerCode": None,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/query")
            .get("/ops/api/ticket/query?")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/editTicketStatus")
            .patch("/ops/api/ticket/editTicketStatus")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"ticketCode": "$ticketCode", "ticketStatus": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/query")
            .get("/ops/api/ticket/query?")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/promotion/getPromotionItemList")
            .get("/ops/api/promotion/getPromotionItemList")
            .with_params(
                **{
                    "qp-activityNo-eq": "$activityNo",
                    "currentPage": "1",
                    "pageSize": "500",
                }
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/getDetail")
            .get("/ops/api/ticket/getDetail")
            .with_params(**{"code": "$ticketCode"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/sku/getSkuList")
            .get("/ops/api/sku/getSkuList")
            .with_params(**{"pageSize": "10", "currentPage": "1"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/editTicketStatus")
            .patch("/ops/api/ticket/editTicketStatus")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "id": "$id",
                    "ticketCode": "$ticketCode",
                    "ticketAmount": 100,
                    "ticketOccupied": 0,
                    "ticketUsed": 0,
                    "releaseTime": "$releaseTime",
                    "stopTime": "$stopTime",
                    "activityNo": "$activityNo",
                    "ticketType": 1,
                    "ticketDesc": "$ticketDesc",
                    "ticketStatus": 2,
                    "ticketRange": 1,
                    "releaseType": 2,
                    "ticketUrl": "$ticketUrl",
                    "effectivetimeStart": "$releaseTime",
                    "effectivetimeEnd": "$stopTime",
                    "ticketRules": {
                        "configurations": {
                            "CHANNEL_RULE": {
                                "values": [
                                    {
                                        "enable": True,
                                        "name": "电商",
                                        "type": [
                                            {
                                                "enable": True,
                                                "name": "全部店铺",
                                                "value": "1",
                                            },
                                            {
                                                "enable": False,
                                                "name": "部分店铺",
                                                "value": "2",
                                            },
                                        ],
                                        "value": "1",
                                    }
                                ],
                                "name": "活动平台",
                                "id": "",
                                "desc": "活动平台",
                                "group": "group",
                            },
                            "PROMOTION_RULE": {
                                "values": [{"range": "1000", "value": "1"}],
                                "name": "优惠券活动规则",
                                "id": "overoff",
                                "desc": "满减优惠券，满range元减value;满折优惠券，满range元折value;单品优惠券，range为0元减value;",
                                "group": "group",
                            },
                            "USER_RULE": {
                                "values": [
                                    {"enable": True, "name": "黄金会员", "value": "LV4"},
                                    {"enable": False, "name": "白银会员", "value": "LV3"},
                                    {"enable": False, "name": "青铜会员", "value": "LV2"},
                                    {"enable": False, "name": "铂金会员", "value": "LV5"},
                                    {"enable": False, "name": "普通会员", "value": "LV1"},
                                ],
                                "name": "会员等级",
                                "id": "",
                                "desc": "活动会员等级",
                                "group": "group",
                            },
                            "USE_RANGE_TYPE": {
                                "values": [
                                    {"enable": True, "name": "全部商品", "value": "all"},
                                    {"enable": False, "name": "部分商品", "value": "part"},
                                ],
                                "name": "商品范围",
                                "id": "USE_RANGE_TYPE",
                                "desc": "商品范围",
                                "group": "radio",
                            },
                            "OVERLYING_RULE": {
                                "values": [
                                    {"enable": True, "name": "单品活动", "value": "1"},
                                    {"enable": True, "name": "订单活动", "value": "2"},
                                    {"enable": False, "name": "单品优惠券", "value": "3"},
                                    {"enable": False, "name": "订单优惠券", "value": "4"},
                                ],
                                "name": "叠加规则",
                                "id": "",
                                "desc": "叠加规则",
                                "group": "group",
                            },
                            "TICKET_GET_LIMIT_TYPE": {
                                "values": [
                                    {
                                        "number": "2",
                                        "enable": True,
                                        "name": "限制",
                                        "value": "limit",
                                    }
                                ],
                                "name": "领取限制",
                                "id": "TICKET_GET_LIMIT_TYPE",
                                "desc": "limit：个数 numer:领取限制数量",
                                "group": "radio",
                            },
                        }
                    },
                    "rejectOpinion": None,
                    "ticketChannel": None,
                    "createUserId": "1",
                    "modifyUserId": "1",
                    "ticketName": "$ticketName",
                    "platformId": "0",
                    "receiveEffectivetime": None,
                    "ticketLabelType": None,
                    "createUserName": "$createUserName",
                    "modifyUserName": "$modifyUserName",
                    "createTime": None,
                    "modifyTime": None,
                    "bg": "1",
                    "ticketOwnerCode": "0",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/query")
            .get("/ops/api/ticket/query?")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/editTicketStatus")
            .patch("/ops/api/ticket/editTicketStatus")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Content-Type": "application/json; charset=utf-8",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"ticketCode": "$ticketCode", "ticketStatus": 6})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/query")
            .get("/ops/api/ticket/query?")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticketDetail/queryPage")
            .get("/ops/api/ticketDetail/queryPage")
            .with_params(
                **{
                    "currentPage": "1",
                    "pageSize": "10",
                    "qp-ticketCode-eq": "$ticketCode",
                }
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticketDetail/queryPage")
            .get("/ops/api/ticketDetail/queryPage")
            .with_params(**{"qp-ticketCode-eq": "$ticketCode"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/ops/api/ticket/query")
            .get("/ops/api/ticket/query?")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json",
                    "x-app-id": "$x_app_id",
                    "x-tenant-id": "$x_tenant_id",
                    "sso_sessionid": "$sessionId",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Token": "$token",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
    ]


if __name__ == "__main__":
    TestCaseAddAndDeleteCoupon().test_start()
