# NOTE: Generated By HttpRunner v3.1.4
# FROM: commlist.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase, Parameters
from testcases.api.mall.web_pcLogin_test import TestCaseWebPCLogin as Login
import pytest


class TestCaseItemGetCustomerFollowList(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters({
            "phoneNumber-verifyCode": "${parameterize(common.csv)}",
            "qp_customerId_eq-qp_storeCode_eq-sorter-pageSize": "${parameterize(testcases/api/mall/item/item_getCustomerFollowList.csv)}",
        })
    )
    def test_start(self, param) -> "HttpRunner":
        super().test_start(param)

    config = (
        Config("testcase description")
        .base_url("${get_base_url()}")
        .variables(**{
            "x_tenant_id": "2",  # tenant Default value : 2     必填选项  header部分
        })
        .verify(False)
    )

    teststeps = [
        Step(
            RunTestCase("")
            .call(Login)
            .export(*["sessionId", "token"])
        ),
        Step(
            RunRequest("/mall/item/getCustomerFollowList")
            .get("/mall/item/getCustomerFollowList")
            .with_params(
                **{
                    "currentPage": "1",
                    "pageSize": "",
                    "qp-customerId-eq": "$qp_customerId_eq",
                    "qp-storeCode-eq": "$qp_storeCode_eq",
                    "sorter": "$sorter"
                }
            )
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
    ]


if __name__ == "__main__":
    TestCaseCommlist().test_start()
