# NOTE: Generated By HttpRunner v3.1.4
# FROM: 从猜你喜欢进入到商品详情.har
"""
@author :springfall

"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import pytest
from httprunner import Parameters
from testcases.login_test.login_test import TestCaseLogin as Login


class TestCaseEnterFromYouLike(HttpRunner):

    @pytest.mark.parametrize(
        'param',
        Parameters(
            {
                "phoneNumber-verifyCode-storeCode": "${parameterize(common.csv)}",
                'good_name': "${get_good_name()}",
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("从猜你喜欢进入到商品详情")
        .base_url("${get_base_url()}")
        .verify(False)
    )

    teststeps = [
        Step(RunTestCase("login").call(Login).export(*['sessionId', 'token', 'accountCode', 'personId', "name", "nickname", "username", "phone", "memberCode", "userCode"])),

        Step(
            RunRequest("/mall/cmsTemplate/getTemplateByStoreCode")
                .get("/mall/cmsTemplate/getTemplateByStoreCode")
                .with_params(
                **{
                    "qp-storeCode-eq": "$storeCode",
                    "qp-bg-eq": "1",
                    "qp-platform-eq": "2",
                }
            )
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
                .assert_equal("body.code", "000000")
                .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/homeTemplate/getItemPagerByYourLike")
                .get("/mall/homeTemplate/getItemPagerByYourLike")
                .with_params(**{"qp-storeCode-eq": "$storeCode", "pageSize": "12"})
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
                .assert_equal("body.code", "000000")
                .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/cart/cartTotalNum")
                .get("/mall/cart/cartTotalNum")
                .with_params(
                **{
                    "cartType": "1",
                    "channel": "1",
                    "pageSize": "50",
                    "qp-buyerCode-eq": "$accountCode",
                    "qp-cartType-eq": "0",
                    "qp-channelId-eq": "1",
                    "qp-storeCode-eq": "$storeCode",
                }
            )
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
                .assert_equal("body.code", "000000")
                .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/web/getVerificationCode")
                .get("/mall/web/getVerificationCode")
                .with_params(**{"page": "1"})
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
                .assert_equal("body.code", "000000")
                .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/category/queryCategoryTree")
                .get("/mall/category/queryCategoryTree")
                .with_params(**{"status": "0"})
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
                .assert_equal("body.code", "000000")
                .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/homeTemplate/selectDefaultStoreAndSort")
                .get(
                "/mall/homeTemplate/selectDefaultStoreAndSort"
            )
                .with_params(**{"businessType": "phonix", "type": "pc"})
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/item/getItemList")
            .get("/mall/item/getItemList")
            .with_params(
                **{
                    "qp-status-eq": "1",
                    "qp-storeCode-eq": "$storeCode",
                    "frontCategoryId": "1259763232103641089",
                    "totalCount": "0",
                    "currentPage": "1",
                    "pageSize": "16",
                    "sorter-complex": "asc",
                }
            )
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/cart/cartTotalNum")
            .get("/mall/cart/cartTotalNum")
            .with_params(
                **{
                    "cartType": "1",
                    "channel": "1",
                    "pageSize": "50",
                    "qp-buyerCode-eq": "$accountCode",
                    "qp-cartType-eq": "0",
                    "qp-channelId-eq": "1",
                    "qp-storeCode-eq": "$storeCode",
                }
            )
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/category/queryCategoryTree")
            .get("/mall/category/queryCategoryTree")
            .with_params(**{"status": "0"})
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/homeTemplate/selectDefaultStoreAndSort")
            .get(
                "/mall/homeTemplate/selectDefaultStoreAndSort"
            )
            .with_params(**{"businessType": "phonix", "type": "pc"})
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/cart/cartTotalNum")
                .get("/mall/cart/cartTotalNum")
                .with_params(
                **{
                    "cartType": "1",
                    "channel": "1",
                    "pageSize": "50",
                    "qp-buyerCode-eq": "$accountCode",
                    "qp-cartType-eq": "0",
                    "qp-channelId-eq": "1",
                    "qp-storeCode-eq": "$storeCode",
                }
            )
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
                .assert_equal("body.code", "000000")
                .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/item/oneItem")
                .get("/mall/item/oneItem")
                .with_params(
                **{
                    "qp-storeCode-eq": "$storeCode",
                    "qp-itemCode-eq": "XHITEM1909231519225810977",
                    "loginStatus": "loginStatus",
                }
            )
                .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
                .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
                .assert_equal("body.code", "000000")
                .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/browsingHistory/save")
            .post("/mall/browsingHistory/save")
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .with_json(
                {
                    "browsingDate": "2020-08-14T01:52:08.823Z",
                    "code": 2,
                    "itemCode": "XHITEM1901062004468220831",
                    "storeCode": "$storeCode",
                    "userId": "1282965982368890881",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/item/selectActivityAndTicket")
            .get("/mall/item/selectActivityAndTicket")
            .with_params(
                **{
                    "qp-skuCode-in": "XHSKU46849",
                    "qp-storeCode-eq": "$storeCode",
                    "qp-memberCardCode-eq": "$memberCode",
                    "qp-userCode-eq": "$accountCode",
                }
            )
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/item/getItemList")
            .get("/mall/item/getItemList")
            .with_params(
                **{
                    "frontCategoryId": "1259828936680345611",
                    "byClassIds": "1259828941533155336",
                    "currentPage": "1",
                    "mustNot": "XHITEM1901062004468220831",
                    "qp-storeCode-eq": "$storeCode",
                }
            )
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/mall/item/getCommentList")
            .get("/mall/item/getCommentList")
            .with_params(
                **{"qp-skuCode-eq": "XHSKU46849", "pageSize": "10", "currentPage": "1"}
            )
            .with_headers(
                **{
                    "x-tenant-id": "2",
                    "sso_sessionid": "$sessionId",
                }
            )
            .with_cookies(
                **{
                    "sessionId": "$sessionId",
                    "token": "$token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
        ),
    ]


if __name__ == "__main__":
    TestCaseEnterFromYouLike().test_start()
