# NOTE: Generated By HttpRunner v3.1.4
# FROM: tick.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTick(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/business/api/ticket/query")
            .get("https://cs1.jsbooks.com.cn/business/api/ticket/query")
            .with_params(
                **{
                    "qp-ticketName-like": "自动化测试api测试优惠券",
                    "qp-ticketCode-eq": "TK20200902000002",
                    "qp-createTime-ge": "2020-09-02 00:00:00",
                    "qp-createTime-le": "2020-09-17 23:59:59",
                    "qp-effectivetimeStart-ge": "2020-09-02 00:00:00",
                    "qp-effectivetimeStart-le": "2020-09-27 23:59:59",
                    "qp-ticketType-in": "1",
                    "qp-ticketStatus-in": "0",
                }
            )
            .with_headers(
                **{
                    "Host": "cs1.jsbooks.com.cn",
                    "Connection": "keep-alive",
                    "x-app-id": "201",
                    "x-tenant-id": "2",
                    "sso_sessionid": "1283582626497691650_1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44",
                    "Accept": "application/json",
                    "store-code": "STORE000086",
                    "business-code": "AB1283582626417999874",
                    "token": "eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiIxMjgzNTgyNjI2NDk3NjkxNjUwIiwidXNlciI6eyJwZXJzb25JZCI6bnVsbCwibmFtZSI6bnVsbCwidXNlckNvZGUiOm51bGwsInBlcnNvbk5hbWUiOm51bGwsImFjY291bnRJZCI6MTI4MzU4MjYyNjQ5NzY5MTY1MCwiYWNjb3VudE5hbWUiOiLmtYvor5XllYblrrYiLCJhY2NvdW50Q29kZSI6IkFCMTI4MzU4MjYyNjQxNzk5OTg3NCIsImltZ1VybCI6bnVsbCwidWNJZCI6bnVsbCwidWNJZEFwcGx5U3RhdHVzIjpudWxsLCJ1Y0lkU3RhdHVzIjpudWxsLCJyZXNvdXJjZUlkcyI6bnVsbCwidXNlcm5hbWUiOiLmtYvor5Xlupfpk7oiLCJ0ZW5hbnRJZCI6MiwibG9nb2luQ291bnQiOm51bGwsImVtcGxveWVlQ29kZSI6bnVsbCwiZW1wbG95ZWVOYW1lIjoi5rWL6K-V5ZWG5a62IiwiZW1wbG95ZWVJZCI6MTI4MzU4MjYyNjU1MjIxNzYwMn0sImlhdCI6MTU5OTAxMzk0NSwiZXhwIjoxNjAwNzY2OTc4fQ.rDMclGKDH7FHZVMhLwBiVa9aLMLM50o0wrutslCx4zhi3F3trGi3WF3QVUfDQXxTaokoGegozDP_Eb2lRJV0Xw",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://cs1.jsbooks.com.cn/business/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", "000000")
            .assert_equal("body.msg", "Success")
            .assert_equal("body.traceId", "")
        ),
    ]


if __name__ == "__main__":
    TestCaseTick().test_start()
